### ISSUE TITLE
Question: esp8266 doesn't respond reset command "AT+RST"

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/esp8266-driver#44]
I got some failure after bootloader starts downloaded firmware through wifi.
I compared good case and bad case as following. 
I had updated esp8266 firmware following [this guide](https://developer.mbed.org/teams/ESP8266/wiki/Firmware-Update)
It is possible to avoid the bad case? or lowering reproducibility?

good case:  esp8266 module reacts reset command well.

> [BOOT] New active firmware is valid
> [BOOT] Application's start address: 0x8020800
> [BOOT] Application's jump address: 0x8021261
> [BOOT] Application's stack address: 0x20018000
> [BOOT] Forwarding to application...
> 9LStart simple mbed Cloud Client
> Start developer flow
> Developer credentials already exists
> [EasyConnect] IPv4 mode
> [EasyConnect] Using WiFi (ESP8266)
> [EasyConnect] Connecting to WiFi botren01
> AT> AT+RST
> AT< AT+RST
> AT<
> AT= OK
> AT<
> AT< 0,CLOSED
> AT< WIFI DISCONNECT
> AT<
> AT<  ets Jan  8 2013,rst cause:1, boot mode:(3,7)
> AT<
> AT< load 0x40100000, len 816, room 16
> AT< tail 0
> AT< chksum 0x8d
> AT< load 0x3ffe8000, len 788, room 8
> AT< tail 12
> AT< chksum 0xcf
> AT< ho 0 tail 12 room 4
> AT< load 0x3ffe8314, len 288, room 12
> AT< tail 4
> AT< chksum 0xcf
> AT< csum 0xcf
> AT<
> AT< 2nd boot version : 1.2
> AT<   SPI Speed      : 40MHz
> AT<   SPI Mode       : QIO
> AT<   SPI Flash Size : 32Mbit
> AT< jump to run user1
> AT<
> AT< Äãœìpƒoì|sƒŸcc
>                   l
>                    lll`Œãœï›lŒlŒT= ready
> _esp.reset() passed.

Bad case : esp8266 doesn't respond reset command.

> [BOOT] New active firmware is valid
> [BOOT] Application's start address: 0x8020800
> [BOOT] Application's jump address: 0x8053861
> [BOOT] Application's stack address: 0x20018000
> [BOOT] Forwarding to application...
> 
> Start simple mbed Cloud Client
> Start developer flow
> Developer credentials already exists
> [EasyConnect] IPv4 mode
> [EasyConnect] Using WiFi (ESP8266)
> [EasyConnect] Connecting to WiFi botren01
> AT> AT+RST
> AT> AT+RST
> get_mac_addres() started.
> AT> AT+CIFSR
> AT<
> AT< busy s...
> AT<
> AT< Recv 34 bytes
> AT<
> AT< SEND OK
> AT<
> AT< +IPD,0,23:[EasyConnect] ERROR - No MAC address
> [EasyConnect] Connection to Network Failed -3012!
> Failed to initialize connection

**Comment by geky** [comment]
Unfortunately, the esp8266 can just end up in some bad states where it won't parse AT+RST command. This is mostly caused by resetting the microcontroller.

Best example: You send AT+SEND 4096 bytes, but the microcontroller is reset halfway through sending the data. Now you would have to send AT+RST 600 times before the esp8266 starts parsing commands again. You will also send a TCP packet as a side-effect, which may be problematic upstream.

The best solution I can think of is to tie the reset lines together. Some packages have the reset line exposed, some just have a reset button. Note, reset lines will need to be untied for firmware updates.

There have been talks of adding a pin argument for the reset line, but no one has had the time to add it yet.

**Comment by soramame21** [comment]
@geky Thanks for explanation. If we can reset the esp8266 shield after update, that will be perfect.
